### PR TITLE
Deploy to Fly.io

### PR DESCRIPTION
**Pull request by nelsonic**
This PR adds the necessary files to deploy the app to Fly.io

+ [x] create `fly.toml` file for deployment to Fly.io see: https://github.com/dwyl/learn-devops/pull/76
+ [x] create `lib/hits/release.ex` to run migrations on Fly: https://fly.io/docs/getting-started/elixir/#running-migrations-in-production
+ [x] create the `/rel` directory and files: https://fly.io/docs/getting-started/elixir/#generate-release-config-files
+ [x] create `Dockerfile` ... https://fly.io/docs/getting-started/elixir/#dockerfile 🚢  
 Which reminds me: we probably need to update https://github.com/dwyl/learn-docker ... 💭  
+ [x] update to Phoenix `1.6.2` see: https://github.com/dwyl/learn-phoenix-framework/issues/143

Badges work again:  [HitCount](http://hits.dwyl.com/dwyl/hits-pr)

### CODE REVIEW

**Comment by nelsonic** [comment]
```
==> Release command
Command: /app/bin/hits eval Hits.Release.migrate
	 Starting instance
	 Configuring virtual machine
	 Pulling container image
	 Unpacking image
	 Preparing kernel init
	 Configuring firecracker
	 Starting virtual machine
	 Starting init (commit: 50ffe20)...
	 Preparing to run: `/app/bin/hits eval Hits.Release.migrate` as root
	 Error: UnhandledIoError(Os { code: 2, kind: NotFound, message: "No such file or directory" })
	 [    0.078973] Kernel panic - not syncing: Attempted to kill init! exitcode=0x00000100
	 [    0.079860] CPU: 0 PID: 1 Comm: init Not tainted 5.12.2 #1
	 [    0.080444] Call Trace:
	 [    0.081715]  dump_stack+0x63/0x7e
	 [    0.081069]  panic+0xf3/0x2a1
	 [    0.081371]  do_exit+0x967/0xb50
	 [    0.081727]  ? __vm_munmap+0x96/0xd0
	 [    0.082114]  do_group_exit+0x3e/0xa0
	 [    0.082498]  __x64_sys_exit_group+0x13/0x20
	 [    0.082946]  do_syscall_64+0x37/0x50
	 [    0.083331]  entry_SYSCALL_64_after_hwframe+0x44/0xae
	 [    0.084221] RIP: 0033:0x6f18b5
	 [    0.084221] Code: eb ef 48 8b 76 28 e9 76 05 00 00 64 48 8b 04 25 00 00 00 00 48 8b b0 b0 00 00 00 e9 af ff ff ff 48 63 ff b8 e7 00 00 00 0f 05 <ba> 3c 00 00 00 48 89 d0 0f 05 eb f9 66 2e 0f 1f 84 00 00 00 00 00
	 [    0.086175] RSP: 002b:00007ffe16c3e608 EFLAGS: 00000246 ORIG_RAX: 00000000000000e7
	 [    0.086971] RAX: ffffffffffffffda RBX: 00000000005c3c00 RCX: 00000000006f18b5
	 [    0.087739] RDX: 0000000000000000 RSI: 0000000000000000 RDI: 0000000000000001
	 [    0.088466] RBP: 0000000000000001 R08: 0000000000000000 R09: 0000000000000000
	 [    0.089189] R10: 0000000000000000 R11: 0000000000000246 R12: 00007ffe16c3e668
	 [    0.089980] R13: 00007ffe16c3e678 R14: 0000000000000000 R15: 0000000000000000
	 [    0.090730] Kernel Offset: disabled
	 [    0.091099] Rebooting in 1 seconds..

Error Release command failed, deployment aborted
```

**Comment by nelsonic** [comment]
https://community.fly.io/t/elixir-buildpacks-error/1234/15

Solution: remove the lines from `fly.toml` so that Fly will build the App using Docker:

```yml
 [build]
   image = "flyio/hellofly:latest"
```

**Comment by nelsonic** [comment]
Much better:

```
==> Release command
Command: /app/bin/hits eval Hits.Release.migrate
	 Starting instance
	 Configuring virtual machine
	 Pulling container image
	 Unpacking image
	 Preparing kernel init
	 Starting virtual machine
	 Starting init (commit: 50ffe20)...
	 Preparing to run: `/app/bin/hits eval Hits.Release.migrate` as nobody
	 2021/10/31 21:38:16 listening on [fdaa:0:3800:a7b:2808:68ca:f592:2]:22 (DNS: [fdaa::3]:53)
	 Reaped child process with pid: 561 and signal: SIGUSR1, core dumped? false
	 21:38:18.664 [info] == Running 20190515211749 Hits.Repo.Migrations.CreateUsers.change/0 forward
	 21:38:18.669 [info] create table users
	 21:38:18.686 [info] == Migrated 20190515211749 in 0.0s
	 21:38:18.741 [info] create table repositories
	 21:38:18.746 [info] create index repositories_user_id_index
	 21:38:18.769 [info] == Running 20190515211804 Hits.Repo.Migrations.CreateUseragents.change/0 forward
	 21:38:18.769 [info] create table useragents
	 21:38:18.773 [info] == Migrated 20190515211804 in 0.0s
	 21:38:18.784 [info] == Running 20190515211819 Hits.Repo.Migrations.CreateHits.change/0 forward
	 21:38:18.784 [info] create table hits
	 21:38:18.790 [info] create index hits_repo_id_index
	 21:38:18.795 [info] create index hits_useragent_id_index
	 Main child exited normally with code: 0
	 Reaped child process with pid: 563 and signal: SIGUSR1, core dumped? false
	 Starting clean up.
Monitoring Deployment

1 desired, 1 placed, 0 healthy, 0 unhealthy [health checks: 1 total, 1 passing]
```

**Comment by nelsonic** [comment]
Almost there: https://hits.fly.dev ... ⏳ 
hits-almost-working-on-fly-io

**Comment by nelsonic** [comment]
Not quite there yet ... https://hits.fly.dev/test/test.svg
hits-badge-not-working

**Comment by nelsonic** [comment]
Time to learn how to debug on Fly.io ... 💭

**Comment by nelsonic** [comment]
Fairly straightforward:

```
flyctl --app hits logs
```


Log:
```
2021-10-31T22:03:34.313 app[1eb4c9ce] lhr [info] 22:03:34.312 request_id=FrM8r4rPG7blWh0AAASh [info] HEAD /test/test.svg
2021-10-31T22:03:34.320 app[1eb4c9ce] lhr [info] 22:03:34.319 request_id=FrM8r4rPG7blWh0AAASh [info] Sent 500 in 7ms
2021-10-31T22:03:34.321 app[1eb4c9ce] lhr [info] 22:03:34.320 [error] #PID<0.1990.0> running HitsWeb.Endpoint (connection #PID<0.1989.0>, stream id 1) terminated
2021-10-31T22:03:34.321 app[1eb4c9ce] lhr [info] Server: hits.fly.dev:80 (http)
2021-10-31T22:03:34.321 app[1eb4c9ce] lhr [info] Request: HEAD /test/test.svg
2021-10-31T22:03:34.321 app[1eb4c9ce] lhr [info] ** (exit) an exception was raised:
2021-10-31T22:03:34.321 app[1eb4c9ce] lhr [info]     ** (File.Error) could not read file "./lib/hits_web/templates/hit/badge_flat_square.svg": no such file or directory
2021-10-31T22:03:34.321 app[1eb4c9ce] lhr [info]         (elixir 1.12.1) lib/file.ex:355: File.read!/1
2021-10-31T22:03:34.321 app[1eb4c9ce] lhr [info]         (hits 1.0.0) lib/hits.ex:49: Hits.make_badge/2
2021-10-31T22:03:34.321 app[1eb4c9ce] lhr [info]         (hits 1.0.0) lib/hits_web/controllers/hit_controller.ex:78: HitsWeb.HitController.render_badge/3
2021-10-31T22:03:34.321 app[1eb4c9ce] lhr [info]         (hits 1.0.0) lib/hits_web/controllers/hit_controller.ex:1: HitsWeb.HitController.action/2
2021-10-31T22:03:34.321 app[1eb4c9ce] lhr [info]         (hits 1.0.0) lib/hits_web/controllers/hit_controller.ex:1: HitsWeb.HitController.phoenix_controller_pipeline/2
2021-10-31T22:03:34.321 app[1eb4c9ce] lhr [info]         (phoenix 1.5.3) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
2021-10-31T22:03:34.321 app[1eb4c9ce] lhr [info]         (hits 1.0.0) lib/hits_web/endpoint.ex:1: HitsWeb.Endpoint.plug_builder_call/2
2021-10-31T22:03:34.321 app[1eb4c9ce] lhr [info]         (hits 1.0.0) lib/hits_web/endpoint.ex:1: HitsWeb.Endpoint.call/2
```

**Comment by nelsonic** [comment]
Need to ssh into the node to debug: 
https://fly.io/docs/getting-started/elixir/#getting-an-iex-shell-into-a-running-node

**Comment by nelsonic** [comment]
Basically I couldn't figure out how to read the `./lib/hits_web/templates/hit/badge_flat_square.svg` file on Fly.io (it doesn't appear to be there...!) so I just in-lined the SVG in the function as a string which is also _muuuuch_ faster to respond. 💭

**Comment by nelsonic** [comment]
Working: https://hits.dwyl.com/test/test.svg
Screen Shot 2021-10-31 at 10 59 10 PM

**Comment by nelsonic** [comment]
The WebSocket doesn't work:
hits-websockets-dont-work

```
app-5b6e51d159e0479ea09895c0f3d46a4e.js?vsn=d:1 WebSocket connection to 'wss://hits.dwyl.com/socket/websocket?token=undefined&vsn=2.0.0' failed: 
```

**Comment by nelsonic** [comment]
Reading: https://elixirforum.com/t/websockets-not-working-phoenix-scripts-on-sub-domain-loaded-through-main-domain-apache/41871

**Comment by nelsonic** [comment]
Attempt to follow this example: https://stackoverflow.com/a/67305310/1148249

**Comment by nelsonic** [comment]
Well this is fun ... 🙄 
```
23:42:13.153 [error] Task #PID<0.164.0> started from :hex_fetcher terminating
** (UndefinedFunctionError) function :ssl.cipher_suites/1 is undefined or private
    (ssl 10.5.2) :ssl.cipher_suites(:openssl)
    (hex 0.20.5) lib/hex/http/ssl.ex:124: Hex.HTTP.SSL.filter_ciphers/1
    (hex 0.20.5) lib/hex/http/ssl.ex:66: Hex.HTTP.SSL.ssl_opts/1
    (hex 0.20.5) lib/hex/http.ex:41: Hex.HTTP.build_http_opts/2
    (hex 0.20.5) lib/hex/http.ex:16: Hex.HTTP.request/5
    (hex 0.20.5) lib/hex/registry/server.ex:306: anonymous fn/3 in Hex.Registry.Server.prefetch_online/2
    (elixir 1.12.3) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir 1.12.3) lib/task/supervised.ex:35: Task.Supervised.reply/5
Function: #Function<17.86168715/0 in Hex.Registry.Server.prefetch_online/2>
    Args: []

```

**Comment by nelsonic** [comment]
https://git.pleroma.social/pleroma/pleroma/-/issues/2701

```shell
rm -rf _build deps
mix local.hex
mix deps.get
MIX_ENV=prod mix compile
```

**Comment by nelsonic** [comment]
The WebSocket works on: http://hits.fly.dev/
Screen Shot 2021-11-01 at 12 28 45 AM

So I think this might be a Cloudflare issue ...

**Comment by nelsonic** [comment]
Opened a separate issue on the `WebSocket` failure: https://github.com/dwyl/hits/issues/129
Not urgent right now as the badges are working; that's all I wanted. ✅

**Comment by nelsonic** [comment]
Hi @SimonLab, 👋 
I finally managed to focus for long enough to deploy the Hits App to Fly.io https://hits.dwyl.com/ 🚀 
This PR adds the necessary files for the deployment. 📝 
The badges on all our repos work again. ✅ 
Please review/feedback/merge if OK. :shipit: 
Thanks. 👍 

Related to: https://github.com/dwyl/product-roadmap/issues/7

**Review by SimonLab — APPROVED** [review]
Looks good to me!
I mainly focused on checking the upgrade to Phoenix 1.6 is good.
I've installed the fly cli on my computer, I'll have a go at trying to deploy an Elixir app soon
Thanks :+1:

**Comment by nelsonic** [comment]
Thanks @SimonLab ☀️🙌

**Pull request merged**
