### PR TITLE
Revive Hits - Better (Much Faster!) than Ever

### PR DESCRIPTION
**Pull request by nelsonic**
@iteles this PR dusts off the "Hits" project so that we can use it as a "beginners" node.js tutorial.

Issues resolved:
+ Fix/Revive the "Hits" project fixes https://github.com/dwyl/repo-badges/issues/27 and https://github.com/dwyl/repo-badges/issues/24
+ Deploy to "_better_" (_faster/cheaper_) hosting service #37 
+ Created service: http://hits.dwyl.io / http://hits.dwyl.com (MVP) https://github.com/dwyl/hits/issues/22 to avoid the (_slow_) Heroku startup time. 
image

+ Remove use of shields.io "proxy badge" #30 which was _super slow_! instead use our own SVG template. ✅ 
+ fixes: #41 (update dependencies), #43 (record browser language), #44 (simplify code!), #45 (format data in a user-friendly way in browser), #47 (error logging on server when something goes wrong!). 

Using the "curl" response time command https://stackoverflow.com/a/22625150/1148249
we see that response is consistently around 300ms on my _crappy_ 3G connection in PT!
image

This will form part of the _next_ dwyl "learn" tutorial. 
But right now I just want to _ship_ the progress "so far".

### CODE REVIEW

**Comment by nelsonic** [comment]
@iteles no "_rush_" to Merge this, but would be good at `some` point this week when you have time. 😉

**Comment by iteles** [comment]
@nelsonic I just didn't know whether it was ready for merging 😊
Will review this afternoon!

**Comment by nelsonic** [comment]
Added basic UI for creating Badges on the Homepage:
image

**Comment by nelsonic** [comment]
Final "MVP" UI: 
image

@iteles PR assigned. thanks for reviewing/merging.

**Comment by nelsonic** [comment]
@iteles thank you! ❤️

**Pull request merged**
