### PR TITLE
define host as hits.dwyl.com

### PR DESCRIPTION
**Pull request by SimonLab**
ref: #129

### CODE REVIEW

**Review by nelsonic — APPROVED** [review]
@SimonLab looks good. Should the port be `443`? (given that it defaults to HTTPS via Cloudflare)

**Comment by SimonLab** [comment]
Yes I wasn't sure about the port and wanted to test the default one first. I'll check the logs once deployed to see if I need to update the port too :+1:

**Comment by nelsonic** [comment]
Yeah, I thought as much. That's why I merged so you wouldn't have to wait. Hope the exploration is going well. 👍

**Comment by SimonLab** [comment]
I think I'll need to update also the runtime config:
https://github.com/dwyl/hits/blob/6fe81cf5dbc4afc5c5a811fa2ff958d52d2c224a/config/runtime.exs#L17

**Comment by nelsonic** [comment]
Hmm ... could be worth asking on the Fly.io forum e.g: https://community.fly.io/t/phoenix-liveview-hangs-on-websocket-connection-on-all-browsers/3434 to confirm if there's a Doc link we are missing. 💭

**Pull request merged**
