### PR TITLE
Adding support for more badge designs

### PR DESCRIPTION
**Pull request by LuchoTurtle**
Hey Hits team!

Proper repo, mighty appreciated and really useful! I have never programmed in Elixir, let alone dabbled with the Phoenix framework so pardon me if I made idiomatic blasphemies here. Overall, this pull request should address both #99 and #95. I've essentially added support for an additional design (the `flat` one from [shields.io](https://shields.io/)) and updated the frontend accordingly.

More specifically, the user can specify the style through a query param (e.g. `?style=flat`). The `make_badge` function now has a `case` statement, with the default one being the `flat-square` (the design that was only previously available). 

A few tests were added to test this behaviour, as well as refactoring a few to make assertions more relevant. Testing now checks for an `id` in the `.svg` files when asserting, instead of just doing `=~ s(1)`. I might have interpreted the `=~` operator wrong so I'm not sure about this part but you can check if I did something wrong or if my logic is correct!

I'm happy to add the `plastic` design from [shields.io](https://shields.io/) if this is an okay PR!

### CODE REVIEW

**Comment by 178inaba** [comment]
@nelsonic I also want this feature, is it possible to review it?

**Review by samhstn — APPROVED** [review]
Looks good to me @LuchoTurtle

**Review by samhstn — APPROVED** [review]

**Comment by freitzzz** [comment]
@LuchoTurtle @samhstn @nelsonic @iteles 

Any updates on this? Custom styling is a must for todays developers swag needs 😬

**Review by nelsonic — APPROVED** [review]
Great work @LuchoTurtle Thanks! 🚀 
(_this will be deployed to our new host shortly ..._)

**Comment by nelsonic** [comment]
The `flat` badge style is now working   [HitCount](http://hits.dwyl.com/test/test) 🎉 
Thanks again @LuchoTurtle

**Pull request merged**
