### PR TITLE
Update Elixir to v1.12.3

### PR DESCRIPTION
**Pull request by nelsonic**
This PR:
+ [x] Updates `Elixir` to `v1.12.3` #125 
+ [x] Comments out unused code  #126 

@iteles please review/merge when you can.
My next step is to update the version of Phoenix and deploy to Fly.io https://github.com/dwyl/learn-devops/issues/72
But I don't want to make this PR _too_ big. 💭

### CODE REVIEW

**Comment by nelsonic** [comment]
Merge conflicts I need to resolve: 
```
n@MBP hits % git pull origin master --rebase
remote: Enumerating objects: 43, done.
remote: Counting objects: 100% (43/43), done.
remote: Compressing objects: 100% (40/40), done.
remote: Total 40 (delta 24), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (40/40), 14.51 KiB | 200.00 KiB/s, done.
From github.com:dwyl/hits
 * branch            master     -> FETCH_HEAD
   971f459..3b51eb2  master     -> origin/master
Auto-merging test/support/conn_case.ex
CONFLICT (content): Merge conflict in test/support/conn_case.ex
Auto-merging test/support/channel_case.ex
CONFLICT (content): Merge conflict in test/support/channel_case.ex
Auto-merging mix.exs
CONFLICT (content): Merge conflict in mix.exs
Auto-merging lib/hits/application.ex
Auto-merging config/config.exs
CONFLICT (content): Merge conflict in config/config.exs
error: could not apply b33d9f7... upgrade to Phoenix 1.5.3 fixes issue #103
Resolve all conflicts manually, mark them as resolved with
"git add/rm <conflicted_files>", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply b33d9f7... upgrade to Phoenix 1.5.3 fixes issue #103
```

**Comment by nelsonic** [comment]
```
git rebase --continue
[detached HEAD b1ac67a] upgrade to Phoenix 1.5.3 fixes issue #103
 Author: nelsonic <nelson+github@dwyl.io>
 4 files changed, 5 insertions(+), 3 deletions(-)
Auto-merging mix.lock
CONFLICT (content): Merge conflict in mix.lock
Auto-merging mix.exs
CONFLICT (content): Merge conflict in mix.exs
error: could not apply 681c393... upgrade all dependencies to latest versions #103
Resolve all conflicts manually, mark them as resolved with
"git add/rm <conflicted_files>", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply 681c393... upgrade all dependencies to latest versions #103
```

**Comment by nelsonic** [comment]
Migrate to .com https://app.travis-ci.com/github/dwyl/hits
image

**Comment by nelsonic** [comment]
@iteles if you have a couple of minutes, please review/merge this PR. Thanks. 👍

**Comment by iteles** [comment]
Sorry, I've been reviewing this slowly!

**Review by iteles — APPROVED** [review]

**Comment by nelsonic** [comment]
@iteles thanks. ☀️

**Pull request merged**
